# Generated by Django 2.1 on 2020-05-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='category_local',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='community',
            name='category_sectors',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='qna',
            name='category_local',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='qna',
            name='category_sectors',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tipnknowhow',
            name='category_local',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tipnknowhow',
            name='category_sectors',
            field=models.CharField(max_length=30),
        ),
    ]
