# Generated by Django 3.0.6 on 2020-05-28 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopy', '0002_auto_20200525_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='QNA',
            new_name='QnA',
        ),
    ]
